// <auto-generated />
using System;
using HxStudioFileUploadService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HxStudioFileUploadService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120131654_updateSeedDataAndDeliverableTable")]
    partial class updateSeedDataAndDeliverableTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HxStudioFileUploadService.Models.BeforeAfter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AfterDesignFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfterDesignFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfterTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeDesignFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeDesignFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MockupGroupId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MockupGroupId")
                        .IsUnique();

                    b.ToTable("BeforeAfters");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.CaseStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseStudyFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseStudyFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MockupGroupId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MockupGroupId")
                        .IsUnique();

                    b.ToTable("CaseStudies");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Deliverable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliverableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessTypeId");

                    b.ToTable("Deliverables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliverableName = "Empathy Mapping",
                            ProcessTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeliverableName = "Journey Mapping",
                            ProcessTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            DeliverableName = "Task Flow",
                            ProcessTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            DeliverableName = "Personas",
                            ProcessTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            DeliverableName = "Scenarios",
                            ProcessTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            DeliverableName = "Heuristic Evaluation",
                            ProcessTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            DeliverableName = "Information Architecture (Block Diagram)",
                            ProcessTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            DeliverableName = "Low-hi Fidelity Wireframes",
                            ProcessTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            DeliverableName = "Prototype",
                            ProcessTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            DeliverableName = "Research Report",
                            ProcessTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            DeliverableName = "Branding Style Guide",
                            ProcessTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            DeliverableName = "Visual Design",
                            ProcessTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            DeliverableName = "Design System (Assets, Micro interactions)",
                            ProcessTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            DeliverableName = "Clickable Prototype",
                            ProcessTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            DeliverableName = "HTML CSS Markups",
                            ProcessTypeId = 4
                        },
                        new
                        {
                            Id = 16,
                            DeliverableName = "Atomic Design",
                            ProcessTypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            DeliverableName = "Accessibilty Compliance(WCAG)",
                            ProcessTypeId = 4
                        },
                        new
                        {
                            Id = 18,
                            DeliverableName = "React/Angular based components",
                            ProcessTypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            DeliverableName = "Competitor Analysis",
                            ProcessTypeId = 1
                        });
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Domain");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MockupGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "MockupGroupId");

                    b.HasIndex("MockupGroupId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Mockup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MockupGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MockupGroupId");

                    b.ToTable("Mockups");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.MockupGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<int>("MockupTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubDomainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("MockupTypeId");

                    b.HasIndex("SubDomainId");

                    b.ToTable("MockupGroups");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.MockupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MockupTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Visual Samples"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Case Studies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Process Diagram & Artifacts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Before After"
                        });
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.ProcessDiagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliverableFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliverableFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliverableId")
                        .HasColumnType("int");

                    b.Property<string>("DeliverableLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliverableId");

                    b.HasIndex("ProcessTypeId");

                    b.ToTable("ProcessDiagrams");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.ProcessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProcessName = "Discover"
                        },
                        new
                        {
                            Id = 2,
                            ProcessName = "Define"
                        },
                        new
                        {
                            Id = 3,
                            ProcessName = "Design"
                        },
                        new
                        {
                            Id = 4,
                            ProcessName = "Develop"
                        });
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Subdomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Subdomain");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MockupGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MockupGroupId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.BeforeAfter", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.MockupGroup", "MockupGroup")
                        .WithOne("BeforeAfter")
                        .HasForeignKey("HxStudioFileUploadService.Models.BeforeAfter", "MockupGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockupGroup");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.CaseStudy", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.MockupGroup", "MockupGroup")
                        .WithOne("CaseStudy")
                        .HasForeignKey("HxStudioFileUploadService.Models.CaseStudy", "MockupGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockupGroup");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Deliverable", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.ProcessType", "ProcessType")
                        .WithMany()
                        .HasForeignKey("ProcessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessType");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Like", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.MockupGroup", "MockupGroup")
                        .WithOne("Like")
                        .HasForeignKey("HxStudioFileUploadService.Models.Like", "MockupGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockupGroup");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Mockup", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.MockupGroup", "MockupGroup")
                        .WithMany("Mockups")
                        .HasForeignKey("MockupGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockupGroup");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.MockupGroup", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HxStudioFileUploadService.Models.MockupType", "MockupType")
                        .WithMany()
                        .HasForeignKey("MockupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HxStudioFileUploadService.Models.Subdomain", "SubDomain")
                        .WithMany()
                        .HasForeignKey("SubDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("MockupType");

                    b.Navigation("SubDomain");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.ProcessDiagram", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.Deliverable", "Deliverable")
                        .WithMany()
                        .HasForeignKey("DeliverableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HxStudioFileUploadService.Models.ProcessType", "ProcessType")
                        .WithMany()
                        .HasForeignKey("ProcessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliverable");

                    b.Navigation("ProcessType");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Subdomain", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.Tag", b =>
                {
                    b.HasOne("HxStudioFileUploadService.Models.MockupGroup", "MockupGroup")
                        .WithMany("Tags")
                        .HasForeignKey("MockupGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockupGroup");
                });

            modelBuilder.Entity("HxStudioFileUploadService.Models.MockupGroup", b =>
                {
                    b.Navigation("BeforeAfter");

                    b.Navigation("CaseStudy");

                    b.Navigation("Like");

                    b.Navigation("Mockups");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
